import { FormEvent, ReactNode, useCallback, useEffect, useMemo, useState } from "react";
import type { DeviceAuth } from "./App";

type BoardItem = { id:string; kind:"notice"|"memo"; title:string; body:string; priority:"normal"|"important"; visibility:string; startsOn:string; endsOn:string; pushEnabled:boolean; recipients:string[]; version:number; summarized?:boolean; archivedAt?:string; deletedAt?:string };
type BoardForm = { kind:"notice"|"memo"; title:string; body:string; priority:"normal"|"important"; visibility:string; startsOn:string; endsOn:string; pushEnabled:boolean; recipients:string[]; version:number };
type Place = { id:string; name:string; regionLabel:string; latitude:number; longitude:number; isHome:boolean; version:number };
type PlaceForm = { name:string; regionLabel:string; latitude:string; longitude:string; isHome:boolean; version:number };
type WeatherResult = { status:"fresh"|"stale"|"unavailable"|"unconfigured"; fetchedAt?:string; place?:Place; forecast?:{ current?:{temperature_2m:number;weather_code:number}; hourly?:{time:string[];temperature_2m:number[];precipitation_probability:number[];weather_code:number[]}; daily?:{time:string[];temperature_2m_max:number[];temperature_2m_min:number[];precipitation_probability_max:number[]} } };
type Widget = "board"|"schedule"|"tasks"|"weather"|"status";
type DeviceType = "trusted_pc"|"parent_mobile"|"shared_tablet"|"tv";
const widgetLabels:Record<Widget,string>={board:"공지·메모",schedule:"일정",tasks:"할 일",weather:"날씨",status:"가족 상태"};
const deviceLabels:Record<DeviceType,string>={trusted_pc:"관리자 PC",parent_mobile:"부모 모바일",shared_tablet:"공용 태블릿",tv:"TV"};
const configurableWidgets:Widget[]=["status","schedule","tasks","board","weather"];

export function C5Dashboard({auth,schedule,tasks,showPreferences=true}:{auth:DeviceAuth|null;schedule:ReactNode;tasks:ReactNode;showPreferences?:boolean}){
  const [widgets,setWidgets]=useState<Widget[]>(["schedule","tasks","board","weather"]);
  const load=useCallback(async()=>{if(!auth)return;const response=await fetch("/api/v1/dashboard-preferences",{cache:"no-store"});if(response.ok){const body=await response.json();setWidgets(body.widgets as Widget[]);}},[auth]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),60_000);return()=>window.clearInterval(timer);},[load]);
  const content:Record<Exclude<Widget,"status">,ReactNode>={board:<BoardSection auth={auth}/>,schedule,tasks,weather:<WeatherSection auth={auth}/>};
  const visibleWidgets=widgets.filter((key):key is Exclude<Widget,"status">=>key!=="status");
  const familyTabWidgets:Exclude<Widget,"status">[]=showPreferences?visibleWidgets:["schedule",...visibleWidgets.filter(key=>key!=="schedule")];
  return <><div className={`dashboard-widgets device-${auth?.device.type||"unknown"}`}>{familyTabWidgets.map(key=><div className={`widget widget-${key}`} key={key}>{content[key]}</div>)}</div>{showPreferences&&auth?.permissions.admin&&<WidgetPreferences auth={auth} onCurrentSaved={load}/>}</>;
}

export function DashboardPreferences({auth}:{auth:DeviceAuth|null}){return auth?.permissions.admin?<WidgetPreferences auth={auth} onCurrentSaved={()=>undefined}/>:null}

function BoardSection({auth}:{auth:DeviceAuth|null}){
  const today=new Date().toLocaleDateString("sv-SE");
  const emptyForm=():BoardForm=>({kind:"notice",title:"",body:"",priority:"normal",visibility:"family",startsOn:today,endsOn:"",pushEnabled:false,recipients:["dad","mom"],version:0});
  const [items,setItems]=useState<BoardItem[]>([]);const [archive,setArchive]=useState<BoardItem[]>([]);const [trash,setTrash]=useState<BoardItem[]>([]);
  const [form,setForm]=useState<BoardForm>(emptyForm);const [editingId,setEditingId]=useState("");const [open,setOpen]=useState(false);const [management,setManagement]=useState<""|"archive"|"trash">("");const [error,setError]=useState("");
  const load=useCallback(async()=>{if(!auth)return;const requests=[fetch("/api/v1/board-items",{cache:"no-store"})];if(auth.permissions.admin)requests.push(fetch("/api/admin/board-archive",{cache:"no-store"}),fetch("/api/admin/board-trash",{cache:"no-store"}));const responses=await Promise.all(requests);if(responses[0].ok)setItems((await responses[0].json()).items||[]);if(responses[1]?.ok)setArchive((await responses[1].json()).items||[]);if(responses[2]?.ok)setTrash((await responses[2].json()).items||[]);},[auth]);
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),60_000);return()=>window.clearInterval(timer);},[load]);
  function closeForm(){setForm(emptyForm());setEditingId("");setOpen(false);setError("");}
  async function submit(event:FormEvent){event.preventDefault();setError("");const response=await fetch(editingId?`/api/v1/board-items/${editingId}`:"/api/v1/board-items",{method:editingId?"PUT":"POST",headers:jsonHeaders(),body:JSON.stringify(form)});if(!response.ok){setError(await apiMessage(response,"게시 항목을 저장하지 못했습니다."));return}closeForm();void load();}
  function edit(item:BoardItem){setForm({kind:item.kind,title:item.title,body:item.body,priority:item.priority,visibility:item.visibility,startsOn:item.startsOn,endsOn:item.endsOn||"",pushEnabled:item.pushEnabled,recipients:item.recipients||["dad","mom"],version:item.version});setEditingId(item.id);setOpen(true);requestAnimationFrame(()=>document.querySelector(".board-editor")?.scrollIntoView({behavior:"smooth",block:"center"}));}
  async function status(item:BoardItem,mode:"archive"|"trash"|"publish"|"restore"|"delete"){const routes={archive:[`/api/v1/board-items/${item.id}/archive`,"POST"],trash:[`/api/v1/board-items/${item.id}`,"DELETE"],publish:[`/api/v1/board-items/${item.id}/publish`,"POST"],restore:[`/api/admin/board-trash/${item.id}/restore`,"POST"],delete:[`/api/admin/board-trash/${item.id}`,"DELETE"]} as const;const [url,method]=routes[mode];if(mode==="delete"&&!window.confirm("이 게시 항목을 영구 삭제할까요? 되돌릴 수 없습니다."))return;const response=await fetch(url,{method,headers:jsonHeaders(),body:JSON.stringify({version:item.version})});if(!response.ok)setError(await apiMessage(response,"게시 항목 상태를 변경하지 못했습니다."));else void load();}
  return <section className="domain-card"><div className="section-heading"><div><p className="label">가족 게시판</p><strong>{items.length?`${items.length}개 게시 중`:"등록된 공지 없음"}</strong></div>{auth?.permissions.admin&&<button type="button" onClick={()=>open?closeForm():setOpen(true)}>{open?"입력 닫기":"공지·메모 추가"}</button>}</div>
    {open&&<form className="domain-form board-editor" onSubmit={submit}><div className="management-heading"><strong>{editingId?"게시 항목 수정":"새 게시 항목"}</strong>{editingId&&<button type="button" className="secondary" onClick={closeForm}>수정 취소</button>}</div><label><span>종류</span><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as BoardForm["kind"]})}><option value="notice">공지</option><option value="memo">메모</option></select></label><label><span>제목</span><input maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label><span>내용</span><textarea maxLength={4000} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} required/></label><div className="form-grid"><label><span>중요도</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as BoardForm["priority"]})}><option value="normal">보통</option><option value="important">중요</option></select></label><label><span>공개 범위</span><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="family">가족 공개</option><option value="tv_summary">TV 요약</option><option value="parents_only">부모 전용</option></select></label><label><span>게시 시작일</span><input type="date" value={form.startsOn} onChange={e=>setForm({...form,startsOn:e.target.value})}/></label><label><span>종료일</span><input type="date" value={form.endsOn} onChange={e=>setForm({...form,endsOn:e.target.value})}/></label></div>{form.kind==="notice"&&form.priority==="important"&&<><label className="recurrence-toggle"><input type="checkbox" checked={form.pushEnabled} onChange={e=>setForm({...form,pushEnabled:e.target.checked})}/><span>부모 모바일 Push 발송</span></label>{form.pushEnabled&&<fieldset><legend>알림 수신자</legend><div className="participant-options">{[["dad","아빠 모바일"],["mom","엄마 모바일"]].map(([owner,label])=><label key={owner}><input type="checkbox" checked={form.recipients.includes(owner)} onChange={()=>setForm({...form,recipients:form.recipients.includes(owner)?form.recipients.filter(value=>value!==owner):[...form.recipients,owner]})}/><span>{label}</span></label>)}</div></fieldset>}</>}{error&&<p className="form-error">{error}</p>}<button type="submit">{editingId?"수정 저장":"게시하기"}</button></form>}
    {!open&&error&&<p className="form-error">{error}</p>}<div className="board-list">{items.map(item=><BoardRow key={item.id} item={item}>{auth?.permissions.admin&&<div className="button-row"><button className="secondary" onClick={()=>edit(item)}>수정</button><button className="secondary" onClick={()=>void status(item,"archive")}>보관</button><button className="danger" onClick={()=>void status(item,"trash")}>삭제</button></div>}</BoardRow>)}</div>
    {auth?.permissions.admin&&<div className="board-management"><div className="management-tabs"><button type="button" className="secondary" onClick={()=>setManagement(management==="archive"?"":"archive")}>보관함 {archive.length}</button><button type="button" className="secondary" onClick={()=>setManagement(management==="trash"?"":"trash")}>휴지통 {trash.length}</button></div>{management==="archive"&&<ManagementList empty="보관된 항목이 없습니다." items={archive} actions={item=><><button className="secondary" onClick={()=>void status(item,"publish")}>다시 게시</button><button className="danger" onClick={()=>void status(item,"trash")}>휴지통</button></>}/>} {management==="trash"&&<ManagementList empty="휴지통이 비어 있습니다." items={trash} actions={item=><><button className="secondary" onClick={()=>void status(item,"restore")}>복원</button><button className="danger" onClick={()=>void status(item,"delete")}>영구 삭제</button></>}/>}</div>}
  </section>;
}

function BoardRow({item,children}:{item:BoardItem;children?:ReactNode}){return <article className={item.priority==="important"?"important":""}><div><span className="badge">{item.kind==="notice"?"공지":"메모"}</span><strong>{item.title}</strong><p>{item.summarized?"새 게시 항목이 있습니다.":item.body}</p></div>{children}</article>}
function ManagementList({items,actions,empty}:{items:BoardItem[];actions:(item:BoardItem)=>ReactNode;empty:string}){return <div className="trash-list board-admin-list">{items.length===0&&<p className="empty-state">{empty}</p>}{items.map(item=><BoardRow key={item.id} item={item}><div className="button-row">{actions(item)}</div></BoardRow>)}</div>}

function WeatherSection({auth}:{auth:DeviceAuth|null}){
  const emptyPlace=():PlaceForm=>({name:"",regionLabel:"",latitude:"",longitude:"",isHome:false,version:0});
  const [weather,setWeather]=useState<WeatherResult>({status:"unconfigured"});const [places,setPlaces]=useState<Place[]>([]);const [selectedPlace,setSelectedPlace]=useState("");const [open,setOpen]=useState(false);const [hourlyOpen,setHourlyOpen]=useState(false);const [form,setForm]=useState<PlaceForm>(emptyPlace);const [editingId,setEditingId]=useState("");const [error,setError]=useState("");
  const [range,setRange]=useState({dailyDays:auth?.device.type==="parent_mobile"?2:auth?.device.type==="shared_tablet"?3:5,hourlyHours:24});
  const [searchQuery,setSearchQuery]=useState("");const [searchResults,setSearchResults]=useState<Array<{name:string;regionLabel:string;latitude:number;longitude:number}>>([]);
  const loadPlaces=useCallback(async()=>{if(!auth)return;const response=await fetch("/api/v1/places",{cache:"no-store"});if(response.ok){const next=(await response.json()).places||[];setPlaces(next);setSelectedPlace(current=>current||next.find((p:Place)=>p.isHome)?.id||next[0]?.id||"");}},[auth]);
  const loadWeather=useCallback(async()=>{if(!auth)return;const suffix=selectedPlace?`?placeId=${encodeURIComponent(selectedPlace)}`:"";const response=await fetch(`/api/v1/weather${suffix}`,{cache:"no-store"});if(response.ok)setWeather(await response.json());},[auth,selectedPlace]);
  useEffect(()=>{void loadPlaces();if(auth)void fetch("/api/v1/dashboard-preferences",{cache:"no-store"}).then(async response=>{if(response.ok){const body=await response.json();setRange({dailyDays:body.dailyDays||5,hourlyHours:body.hourlyHours??24})}});},[loadPlaces,auth]);useEffect(()=>{void loadWeather();const timer=window.setInterval(()=>void loadWeather(),10*60_000);return()=>window.clearInterval(timer);},[loadWeather]);
  function create(){setEditingId("");setForm({name:places.length?"":"집",regionLabel:"",latitude:"",longitude:"",isHome:places.length===0,version:0});setOpen(true);setError("");}
  function edit(place:Place){setEditingId(place.id);setForm({name:place.name,regionLabel:place.regionLabel,latitude:String(place.latitude),longitude:String(place.longitude),isHome:place.isHome,version:place.version});setOpen(true);setError("");}
  async function save(event:FormEvent){event.preventDefault();const response=await fetch(editingId?`/api/v1/places/${editingId}`:"/api/v1/places",{method:editingId?"PUT":"POST",headers:jsonHeaders(),body:JSON.stringify({...form,latitude:Number(form.latitude),longitude:Number(form.longitude)})});if(!response.ok){setError(await apiMessage(response,"장소를 저장하지 못했습니다."));return}const saved=await response.json();setSelectedPlace(saved.id);setOpen(false);setEditingId("");setForm(emptyPlace());await loadPlaces();void loadWeather();}
  async function remove(place:Place){if(!window.confirm(`'${place.name}' 장소를 삭제할까요?`))return;const response=await fetch(`/api/v1/places/${place.id}?version=${place.version}`,{method:"DELETE",headers:jsonHeaders()});if(!response.ok){setError(await apiMessage(response,"장소를 삭제하지 못했습니다."));return}setSelectedPlace("");await loadPlaces();void loadWeather();}
  async function search(){if(searchQuery.trim().length<2){setError("지역명을 두 글자 이상 입력하세요.");return}const response=await fetch(`/api/v1/place-search?q=${encodeURIComponent(searchQuery)}`,{cache:"no-store"});if(!response.ok){setError(await apiMessage(response,"장소를 검색하지 못했습니다."));return}setSearchResults((await response.json()).results||[]);setError("");}
  const daily=weather.forecast?.daily;const days=range.dailyDays;const hourly=useMemo(()=>nextHours(weather.forecast?.hourly,range.hourlyHours),[weather.forecast?.hourly,range.hourlyHours]);
  return <section className="domain-card"><div className="section-heading"><div><p className="label">날씨</p><strong>{weather.place?.regionLabel||"날씨 지역 미설정"}</strong></div>{auth?.permissions.admin&&<button type="button" onClick={create}>장소 추가</button>}</div>
    {places.length>0&&<div className="place-selector"><label><span>표시 장소</span><select value={selectedPlace} onChange={e=>setSelectedPlace(e.target.value)}>{places.map(place=><option key={place.id} value={place.id}>{place.name}{place.isHome?" · 기본 집":""}</option>)}</select></label>{auth?.permissions.admin&&<div className="button-row"><button type="button" className="secondary" onClick={()=>{const place=places.find(item=>item.id===selectedPlace);if(place)edit(place)}}>수정</button><button type="button" className="danger" onClick={()=>{const place=places.find(item=>item.id===selectedPlace);if(place)void remove(place)}}>삭제</button></div>}</div>}
    {open&&<form className="domain-form" onSubmit={save}><div className="management-heading"><strong>{editingId?"장소 수정":"장소 추가"}</strong><button type="button" className="secondary" onClick={()=>setOpen(false)}>닫기</button></div><div className="place-search"><label><span>지역 검색</span><input placeholder="예: 동탄, 화성시" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)}/></label><button type="button" className="secondary" onClick={()=>void search()}>검색</button></div>{searchResults.length>0&&<div className="search-results">{searchResults.map((result,index)=><button type="button" className="secondary" key={`${result.latitude}-${result.longitude}-${index}`} onClick={()=>{setForm({...form,name:result.name,regionLabel:result.regionLabel,latitude:String(result.latitude),longitude:String(result.longitude)});setSearchResults([])}}><strong>{result.name}</strong><span>{result.regionLabel}</span></button>)}</div>}<label><span>장소 이름</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label><span>시·군·구 표시명</span><input placeholder="예: 경기도 화성시 동탄구" value={form.regionLabel} onChange={e=>setForm({...form,regionLabel:e.target.value})} required/></label><div className="form-grid"><label><span>위도</span><input type="number" min="-90" max="90" step="0.00001" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})} required/></label><label><span>경도</span><input type="number" min="-180" max="180" step="0.00001" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})} required/></label></div>{form.latitude&&form.longitude&&<a className="map-link" href={`https://www.openstreetmap.org/?mlat=${encodeURIComponent(form.latitude)}&mlon=${encodeURIComponent(form.longitude)}#map=14/${encodeURIComponent(form.latitude)}/${encodeURIComponent(form.longitude)}`} target="_blank" rel="noreferrer">지도에서 위치 확인</a>}<label className="recurrence-toggle"><input type="checkbox" checked={form.isHome} onChange={e=>setForm({...form,isHome:e.target.checked})}/><span>기본 집 날씨로 사용</span></label><p className="security-note">상세 주소는 저장하지 않습니다. 시·군·구 중심 좌표를 사용하세요.</p>{error&&<p className="form-error">{error}</p>}<button type="submit">장소 저장</button></form>}
    {!open&&error&&<p className="form-error">{error}</p>}{weather.status==="unconfigured"?<p className="empty-state">관리자 모드에서 기본 집 날씨 지역을 설정하세요.</p>:weather.status==="unavailable"?<p className="form-error">날씨 정보를 가져올 수 없습니다. 다른 기능은 정상 동작합니다.</p>:<><div className="current-weather"><strong>{Math.round(weather.forecast?.current?.temperature_2m||0)}°</strong><span>{weatherLabel(weather.forecast?.current?.weather_code||0)}</span></div>{weather.status==="stale"&&<p className="stale-warning">마지막 성공 데이터를 표시 중입니다.</p>}<div className="forecast-grid">{daily?.time.slice(0,days).map((day,index)=><article key={day}><span>{new Date(`${day}T00:00:00`).toLocaleDateString("ko-KR",{weekday:"short"})}</span><strong>{Math.round(daily.temperature_2m_max[index])}° / {Math.round(daily.temperature_2m_min[index])}°</strong><small>비 {daily.precipitation_probability_max[index]??0}%</small></article>)}</div>{hourly.length>0&&<><button type="button" className="secondary hourly-toggle" onClick={()=>setHourlyOpen(value=>!value)}>{hourlyOpen?"시간별 예보 닫기":"24시간 예보 보기"}</button>{hourlyOpen&&<div className="hourly-forecast">{hourly.map(entry=><article key={entry.time}><span>{new Date(entry.time).toLocaleTimeString("ko-KR",{hour:"2-digit",minute:"2-digit"})}</span><strong>{Math.round(entry.temperature)}°</strong><small>{weatherLabel(entry.code)} · 비 {entry.rain??0}%</small></article>)}</div>}</>}<small>마지막 갱신 {weather.fetchedAt&&new Date(weather.fetchedAt).toLocaleString("ko-KR")}</small></>}</section>;
}

function WidgetPreferences({auth,onCurrentSaved}:{auth:DeviceAuth;onCurrentSaved:()=>void}){const currentType=auth.device.type as DeviceType;const [open,setOpen]=useState(false);const [target,setTarget]=useState<DeviceType>(currentType);const [draft,setDraft]=useState<Widget[]>([]);const [dailyDays,setDailyDays]=useState(5);const [hourlyHours,setHourlyHours]=useState(24);const [error,setError]=useState("");const load=useCallback(async(type:DeviceType)=>{const response=await fetch(`/api/v1/dashboard-preferences?deviceType=${type}`,{cache:"no-store"});if(response.ok){const body=await response.json();setDraft(body.widgets as Widget[]);setDailyDays(body.dailyDays||5);setHourlyHours(body.hourlyHours??24)}},[]);useEffect(()=>{if(open)void load(target)},[open,target,load]);async function save(){const response=await fetch("/api/v1/dashboard-preferences",{method:"PUT",headers:jsonHeaders(),body:JSON.stringify({deviceType:target,widgets:draft,dailyDays,hourlyHours})});if(response.ok){setError("");if(target===currentType)onCurrentSaved();}else setError(await apiMessage(response,"대시보드 설정을 저장하지 못했습니다."));}function move(index:number,delta:number){const next=[...draft];const to=index+delta;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];setDraft(next)}return <section className="preference-card"><button className="secondary" onClick={()=>setOpen(!open)}>기기별 대시보드 설정</button>{open&&<div className="preference-panel"><label><span>설정할 기기 유형</span><select value={target} onChange={e=>setTarget(e.target.value as DeviceType)}>{(Object.keys(deviceLabels) as DeviceType[]).map(type=><option value={type} key={type}>{deviceLabels[type]}</option>)}</select></label><div className="preference-list">{draft.map((widget,index)=><div key={widget}><span>{widgetLabels[widget]}</span><button className="secondary" onClick={()=>move(index,-1)}>위</button><button className="secondary" onClick={()=>move(index,1)}>아래</button><button className="danger" onClick={()=>setDraft(draft.filter(item=>item!==widget))}>숨김</button></div>)}</div><div className="button-row">{configurableWidgets.filter(item=>!draft.includes(item)).map(item=><button className="secondary" key={item} onClick={()=>setDraft([...draft,item])}>{widgetLabels[item]} 표시</button>)}</div><div className="form-grid"><label><span>일별 예보 범위</span><select value={dailyDays} onChange={e=>setDailyDays(Number(e.target.value))}>{[1,2,3,4,5,6,7].map(day=><option key={day} value={day}>{day}일</option>)}</select></label><label><span>시간별 예보 범위</span><select value={hourlyHours} onChange={e=>setHourlyHours(Number(e.target.value))}>{[0,6,12,24,36,48].map(hour=><option key={hour} value={hour}>{hour===0?"숨김":`${hour}시간`}</option>)}</select></label></div>{error&&<p className="form-error">{error}</p>}<button onClick={()=>void save()}>이 기기 유형에 저장</button></div>}</section>}

function nextHours(hourly:WeatherResult["forecast"] extends infer _ ? {time:string[];temperature_2m:number[];precipitation_probability:number[];weather_code:number[]}|undefined : never,count:number){if(!hourly)return[];const now=Date.now()-30*60*1000;const first=hourly.time.findIndex(value=>new Date(value).getTime()>=now);if(first<0)return[];return hourly.time.slice(first,first+count).map((time,index)=>({time,temperature:hourly.temperature_2m[first+index],rain:hourly.precipitation_probability[first+index],code:hourly.weather_code[first+index]}));}
function jsonHeaders(){return {"Content-Type":"application/json","X-CSRF-Token":cookie("family_dashboard_csrf")}}
function cookie(name:string){const prefix=`${encodeURIComponent(name)}=`;const value=document.cookie.split("; ").find(item=>item.startsWith(prefix));return value?decodeURIComponent(value.slice(prefix.length)):""}
async function apiMessage(response:Response,fallback:string){try{const body=await response.json();return body.message||fallback}catch{return fallback}}
function weatherLabel(code:number){if(code===0)return"맑음";if(code<=3)return"구름";if(code<=48)return"안개";if(code<=67)return"비";if(code<=77)return"눈";if(code<=82)return"소나기";return"뇌우"}
