import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import type { DeviceAuth } from "./App";

type BoardItem = { id:string; kind:"notice"|"memo"; title:string; body:string; priority:"normal"|"important"; visibility:string; startsOn:string; endsOn:string; pushEnabled:boolean; version:number; summarized?:boolean };
type BoardForm = { kind:"notice"|"memo"; title:string; body:string; priority:"normal"|"important"; visibility:string; startsOn:string; endsOn:string; pushEnabled:boolean; version:number };
type Place = { id:string; name:string; regionLabel:string; latitude:number; longitude:number; isHome:boolean; version:number };
type WeatherResult = { status:"fresh"|"stale"|"unavailable"|"unconfigured"; fetchedAt?:string; place?:Place; forecast?:{ current?:{temperature_2m:number;weather_code:number}; daily?:{time:string[];temperature_2m_max:number[];temperature_2m_min:number[];precipitation_probability_max:number[]} } };
type Widget = "board"|"schedule"|"tasks"|"weather"|"status";
const widgetLabels:Record<Widget,string>={board:"공지·메모",schedule:"일정",tasks:"할 일",weather:"날씨",status:"가족 상태"};

export function C5Dashboard({auth,schedule,tasks}:{auth:DeviceAuth|null;schedule:ReactNode;tasks:ReactNode}){
  const [widgets,setWidgets]=useState<Widget[]>(["schedule","tasks","board","weather"]);
  const load=useCallback(async()=>{if(!auth)return;const response=await fetch("/api/v1/dashboard-preferences",{cache:"no-store"});if(response.ok){const body=await response.json();setWidgets((body.widgets as Widget[]).filter(item=>item!=="status"));}},[auth]);
  useEffect(()=>{void load();},[load]);
  const content:Record<Exclude<Widget,"status">,ReactNode>={board:<BoardSection auth={auth}/>,schedule,tasks,weather:<WeatherSection auth={auth}/>};
  return <><div className={`dashboard-widgets device-${auth?.device.type||"unknown"}`}>{widgets.filter((key):key is Exclude<Widget,"status">=>key!=="status").map(key=><div className={`widget widget-${key}`} key={key}>{content[key]}</div>)}</div>{auth?.permissions.admin&&<WidgetPreferences auth={auth} widgets={widgets} onSaved={load}/>}</>;
}

function BoardSection({auth}:{auth:DeviceAuth|null}){
  const today=new Date().toLocaleDateString("sv-SE");
  const initial:BoardForm={kind:"notice",title:"",body:"",priority:"normal",visibility:"family",startsOn:today,endsOn:"",pushEnabled:false,version:0};
  const [items,setItems]=useState<BoardItem[]>([]);const [form,setForm]=useState<BoardForm>(initial);const [editingId,setEditingId]=useState("");const [open,setOpen]=useState(false);const [error,setError]=useState("");
  const load=useCallback(async()=>{if(!auth)return;const response=await fetch("/api/v1/board-items",{cache:"no-store"});if(response.ok)setItems((await response.json()).items||[]);},[auth]);useEffect(()=>{void load();},[load]);
  async function submit(event:FormEvent){event.preventDefault();setError("");const response=await fetch(editingId?`/api/v1/board-items/${editingId}`:"/api/v1/board-items",{method:editingId?"PUT":"POST",headers:jsonHeaders(),body:JSON.stringify(form)});if(!response.ok){setError("게시 항목을 저장하지 못했습니다.");return}setForm(initial);setEditingId("");setOpen(false);void load();}
  function edit(item:BoardItem){setForm({kind:item.kind,title:item.title,body:item.body,priority:item.priority,visibility:item.visibility,startsOn:item.startsOn,endsOn:item.endsOn||"",pushEnabled:item.pushEnabled,version:item.version});setEditingId(item.id);setOpen(true);}
  async function action(item:BoardItem,mode:"archive"|"trash"){const response=await fetch(mode==="trash"?`/api/v1/board-items/${item.id}`:`/api/v1/board-items/${item.id}/archive`,{method:mode==="trash"?"DELETE":"POST",headers:jsonHeaders(),body:JSON.stringify({version:item.version})});if(response.ok)void load();}
  return <section className="domain-card"><div className="section-heading"><div><p className="label">가족 게시판</p><strong>{items.length?`${items.length}개 게시 중`:"등록된 공지 없음"}</strong></div>{auth?.permissions.admin&&<button type="button" onClick={()=>setOpen(!open)}>{open?"입력 닫기":"공지·메모 추가"}</button>}</div>{open&&<form className="domain-form" onSubmit={submit}><label><span>종류</span><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value as "notice"|"memo"})}><option value="notice">공지</option><option value="memo">메모</option></select></label><label><span>제목</span><input maxLength={120} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label><span>내용</span><textarea maxLength={4000} value={form.body} onChange={e=>setForm({...form,body:e.target.value})} required/></label><div className="form-grid"><label><span>중요도</span><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value as "normal"|"important"})}><option value="normal">보통</option><option value="important">중요</option></select></label><label><span>공개 범위</span><select value={form.visibility} onChange={e=>setForm({...form,visibility:e.target.value})}><option value="family">가족 공개</option><option value="tv_summary">TV 요약</option><option value="parents_only">부모 전용</option></select></label><label><span>게시 시작일</span><input type="date" value={form.startsOn} onChange={e=>setForm({...form,startsOn:e.target.value})}/></label><label><span>종료일</span><input type="date" value={form.endsOn} onChange={e=>setForm({...form,endsOn:e.target.value})}/></label></div>{form.kind==="notice"&&form.priority==="important"&&<label className="recurrence-toggle"><input type="checkbox" checked={form.pushEnabled} onChange={e=>setForm({...form,pushEnabled:e.target.checked})}/><span>부모 모바일 Push 발송</span></label>}{error&&<p className="form-error">{error}</p>}<button type="submit">게시하기</button></form>}<div className="board-list">{items.map(item=><article className={item.priority==="important"?"important":""} key={item.id}><div><span className="badge">{item.kind==="notice"?"공지":"메모"}</span><strong>{item.title}</strong><p>{item.summarized?"새 게시 항목이 있습니다.":item.body}</p></div>{auth?.permissions.admin&&<div className="button-row"><button className="secondary" onClick={()=>void action(item,"archive")}>보관</button><button className="danger" onClick={()=>void action(item,"trash")}>삭제</button></div>}</article>)}</div></section>;
}

function WeatherSection({auth}:{auth:DeviceAuth|null}){
  const [weather,setWeather]=useState<WeatherResult>({status:"unconfigured"});const [open,setOpen]=useState(false);const [form,setForm]=useState({name:"집",regionLabel:"",latitude:"",longitude:"",isHome:true});
  const load=useCallback(async()=>{if(!auth)return;const response=await fetch("/api/v1/weather",{cache:"no-store"});if(response.ok)setWeather(await response.json());},[auth]);useEffect(()=>{void load();},[load]);
  async function save(event:FormEvent){event.preventDefault();const response=await fetch("/api/v1/places",{method:"POST",headers:jsonHeaders(),body:JSON.stringify({...form,latitude:Number(form.latitude),longitude:Number(form.longitude)})});if(response.ok){setOpen(false);void load();}}
  const daily=weather.forecast?.daily;const days=auth?.device.type==="parent_mobile"?2:auth?.device.type==="shared_tablet"?3:5;return <section className="domain-card"><div className="section-heading"><div><p className="label">날씨</p><strong>{weather.place?.regionLabel||"날씨 지역 미설정"}</strong></div>{auth?.permissions.admin&&<button type="button" onClick={()=>setOpen(!open)}>{open?"입력 닫기":"장소 설정"}</button>}</div>{open&&<form className="domain-form" onSubmit={save}><label><span>장소 이름</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label><span>시·군·구 표시명</span><input placeholder="예: 서울특별시 강남구" value={form.regionLabel} onChange={e=>setForm({...form,regionLabel:e.target.value})} required/></label><div className="form-grid"><label><span>위도</span><input type="number" min="-90" max="90" step="0.00001" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})} required/></label><label><span>경도</span><input type="number" min="-180" max="180" step="0.00001" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})} required/></label></div><p className="security-note">상세 주소는 저장하지 않습니다. 시·군·구 중심 좌표를 사용하세요.</p><button type="submit">기본 집 날씨 저장</button></form>}{weather.status==="unconfigured"?<p className="empty-state">관리자 모드에서 기본 집 날씨 지역을 설정하세요.</p>:weather.status==="unavailable"?<p className="form-error">날씨 정보를 가져올 수 없습니다. 다른 기능은 정상 동작합니다.</p>:<><div className="current-weather"><strong>{Math.round(weather.forecast?.current?.temperature_2m||0)}°</strong><span>{weatherLabel(weather.forecast?.current?.weather_code||0)}</span></div>{weather.status==="stale"&&<p className="stale-warning">마지막 성공 데이터를 표시 중입니다.</p>}<div className="forecast-grid">{daily?.time.slice(0,days).map((day,index)=><article key={day}><span>{new Date(`${day}T00:00:00`).toLocaleDateString("ko-KR",{weekday:"short"})}</span><strong>{Math.round(daily.temperature_2m_max[index])}° / {Math.round(daily.temperature_2m_min[index])}°</strong><small>비 {daily.precipitation_probability_max[index]??0}%</small></article>)}</div><small>마지막 갱신 {weather.fetchedAt&&new Date(weather.fetchedAt).toLocaleString("ko-KR")}</small></>}</section>;
}

function WidgetPreferences({auth,widgets,onSaved}:{auth:DeviceAuth;widgets:Widget[];onSaved:()=>void}){const [open,setOpen]=useState(false);const [draft,setDraft]=useState<Widget[]>(widgets);useEffect(()=>setDraft(widgets),[widgets]);async function save(){const response=await fetch("/api/v1/dashboard-preferences",{method:"PUT",headers:jsonHeaders(),body:JSON.stringify({deviceType:auth.device.type,widgets:draft})});if(response.ok){setOpen(false);onSaved();}}function move(index:number,delta:number){const next=[...draft];const target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];setDraft(next)}return <section className="preference-card"><button className="secondary" onClick={()=>setOpen(!open)}>이 기기 위젯 순서</button>{open&&<div className="preference-list">{draft.map((widget,index)=><div key={widget}><span>{widgetLabels[widget]}</span><button className="secondary" onClick={()=>move(index,-1)}>위</button><button className="secondary" onClick={()=>move(index,1)}>아래</button><button className="danger" onClick={()=>setDraft(draft.filter(item=>item!==widget))}>숨김</button></div>)}{(["schedule","tasks","board","weather"] as Widget[]).filter(item=>!draft.includes(item)).map(item=><button className="secondary" key={item} onClick={()=>setDraft([...draft,item])}>{widgetLabels[item]} 표시</button>)}<button onClick={()=>void save()}>저장</button></div>}</section>}

function jsonHeaders(){return {"Content-Type":"application/json","X-CSRF-Token":cookie("family_dashboard_csrf")}}
function cookie(name:string){const prefix=`${encodeURIComponent(name)}=`;const value=document.cookie.split("; ").find(item=>item.startsWith(prefix));return value?decodeURIComponent(value.slice(prefix.length)):""}
function weatherLabel(code:number){if(code===0)return"맑음";if(code<=3)return"구름";if(code<=48)return"안개";if(code<=67)return"비";if(code<=77)return"눈";if(code<=82)return"소나기";return"뇌우"}
